sudo: false
dist: bionic
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '12'
  - '10'
  - '8'
  - '6'
after_success:
  - npm run semantic-release
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
